MAKEFLAGS += -j4

NAME = tiscord

# debug or release
COMPILE_MODE = debug

SOURCE_PATH = src
BUILD_PATH = build

COMPLETE_BUILD_PATH = $(BUILD_PATH)/$(RELEASE_MODE)
OBJECT_PATH = $(COMPLETE_BUILD_PATH)/obj

BIN_PATH = $(COMPLETE_BUILD_PATH)/$(NAME)

SOURCES = $(shell find $(SOURCE_PATH) -name "*.cpp")
OBJECTS = $(addprefix $(OBJECT_PATH)/, $(patsubst $(SOURCE_PATH)/%, %, $(SOURCES:.cpp=.o)))

# options for changing the compilation process

CPP_COMPILER = clang++
CPP_VERSION = -std=c++20

CPP_INCLUDE_PATHS = -Iinclude
CPP_LIBRARY_PATHS =
CPP_LIBRARIES =
CPP_OPTIMIZATION = -Og
CPP_WARNING = -Wall
CPP_DEFINES =
CPP_ADDITIONAL_OPTIONS =

ifeq ($(COMPILE_MODE), debug)
	CPP_OPTIMIZATION = -Og
	CPP_WARNING = -Wall
else ifeq ($(COMPILE_MODE), release)
	CPP_OPTIMIZATION = -O3
	CPP_WARNING = -w
endif

CPP_COMPILER_OPTIONS = $(CPP_VERSION) $(CPP_INCLUDE_PATHS) $(CPP_OPTIMIZATION) $(CPP_WARNING) $(CPP_DEFINES) $(CPP_ADDITIONAL_OPTIONS)
CPP_LINKER_OPTIONS = $(CPP_LIBRARIES_PATHS) $(CPP_LIBRARIES)


# rules


.PHONY:
build: $(BIN_PATH)


.PHONY:
run: $(BIN_PATH)
	@ $(BIN_PATH)


$(BIN_PATH): $(OBJECTS)
	@ $(CPP_COMPILER) $(OBJECTS) -o $(BIN_PATH) $(CPP_LINKER_OPTIONS)


$(OBJECTS): $(OBJECT_PATH)/%.o: $(SOURCE_PATH)/%.cpp
	@ mkdir $(dir $@) -p
	@ $(CPP_COMPILER) -c $< -o $@ $(CPP_COMPILER_OPTIONS)


.PHONY:
clean:
	@ rm -r $(BUILD_PATH)
